// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220520170138_CreateInitialSchema")]
    partial class CreateInitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Core.Entities.KanjiAggregate.Kanji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("character");

                    b.HasKey("Id")
                        .HasName("pk_kanji");

                    b.HasIndex("Character")
                        .IsUnique()
                        .HasDatabaseName("ix_kanji_character");

                    b.ToTable("kanji");
                });

            modelBuilder.Entity("Core.Entities.KanjiAggregate.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("label");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_reading");

                    b.HasIndex("KanjiId")
                        .HasDatabaseName("ix_reading_kanji_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_reading_type_id");

                    b.ToTable("reading");
                });

            modelBuilder.Entity("Core.Entities.KanjiAggregate.ReadingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("pk_reading_type");

                    b.ToTable("reading_type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "On"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Kun"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Special"
                        });
                });

            modelBuilder.Entity("Core.Entities.KanjiAggregate.Reading", b =>
                {
                    b.HasOne("Core.Entities.KanjiAggregate.Kanji", null)
                        .WithMany("Readings")
                        .HasForeignKey("KanjiId")
                        .HasConstraintName("fk_reading_kanji_kanji_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.KanjiAggregate.ReadingType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .HasConstraintName("fk_reading_reading_type_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Core.Entities.KanjiAggregate.Kanji", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
